version: "3"

services:
  dotnet-mongodb-api:
    build: .
    image: dotnet-mongodb-api
    ports:
      - "4040:4040"
    links:
      - "db:database"
  db:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"